RechteDB/RechteDB/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from rest_framework import routers
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static

import myRDB.views as views
from . import settings

router = routers.DefaultRouter()

router.register(r'users', views.UsersViewSet, 'user')
router.register(r'useridundnamen', views.TblUserIDundNameViewSet, 'useridundname')
router.register(r'rollen', views.TblRollenViewSet, 'rolle')
router.register(r'afs', views.TblAflisteViewSet, 'af')
router.register(r'afgfs', views.TblUebersichtAfGfsViewSet, 'afgf')
router.register(r'tfs', views.TblTfViewSet, 'tf')

router.register(r'gesamte', views.TblGesamtViewSet, 'gesamt')

router.register(r'appliedroles', views.TblAppliedRolleViewSet, 'appliedrole')
router.register(r'appliedafs', views.TblAppliedAfsViewSet, 'appliedaf')
router.register(r'appliedgfs', views.TblAppliedGfsViewSet, 'appliedgf')
router.register(r'appliedtfs', views.TblAppliedTfsViewSet, 'appliedtf')

router.register(r'orgas', views.TblOrgaViewSet, 'orga')
router.register(r'plattformen', views.TblPlattformViewSet, 'plattform')
router.register(r'gesamtehistorie', views.TblGesamtHistorieViewSet, 'gesamthistorie')
router.register(r'sachgebiete', views.TblsachgebieteViewSet, 'sachgebiet')
router.register(r'subsysteme', views.TblsubsystemeViewSet, 'subsystem')
router.register(r'db2s', views.TblDb2ViewSet, 'db2')
router.register(r'racfgruppen', views.TblRacfGruppenViewSet, 'racfgruppe')
router.register(r'rechteneuvonimport', views.TblrechteneuvonimportViewSet, 'rechtneuvonimport')
router.register(r'rechteamneu', views.TblrechteamneuViewSet, 'rechtamneu')
router.register(r'qriesf3rechteneuvonimportduplikatfrei', views.Qryf3RechteneuvonimportduplikatfreiViewSet,
                'qryf3rechteneuvonimportduplikatfrei')
router.register(r'RACF_Rechte', views.RACF_RechteViewSet, 'RACF_Recht')
router.register(r'Orga_details', views.Orga_detailsViewSet, 'Orga_detail')
router.register(r'letzte_imports', views.Letzter_importViewSet, 'letzter_import')
router.register(r'Modellierungen', views.ModellierungViewSet, 'Modellierung')
router.register(r'Direktverbindungen', views.DirektverbindungenViewSet, 'Direktverbindung')

router.register(r'userhatuseridundnamen', views.UserHatTblUserIDundNameViewSet, 'userhatuseridundname')
router.register(r'userhatrollen', views.TblUserhatrolleViewSet, 'userhatrolle')
router.register(r'rollehatafs', views.TblRollehatafViewSet, 'rollehataf')
router.register(r'afhatgfs', views.TblAfHatGfViewSet, 'afhatgf')
router.register(r'gfhattfs', views.TblGfHatTfViewSet, 'gfhattf')
router.register(r'tfhatschreibweisen', views.TblTfHatSchreibweiseViewSet, 'tfhatschreibweise')

router.register(r'fulluserhatuseridundnamen', views.FullRightsUserHatTblUserIDundNameViewSet,
                'fulluserhatuseridundname')
router.register(r'fullappliedroles', views.FullRightsTblAppliedRolleViewSet, 'fullappliedrole')
router.register(r'fullappliedafs', views.FullRightsTblAppliedAfsViewSet, 'fullappliedaf')
router.register(r'fullappliedgfs', views.FullRightsTblAppliedGfsViewSet, 'fullappliedgf')
router.register(r'fullappliedtfs', views.FullRightsTblAppliedTfsViewSet, 'fullappliedtf')

router.register(r'fullrollen', views.FullTblRollenViewSet, 'fullrolle')
router.register(r'fullafs', views.FullTblAflisteViewSet, 'fullaf')
router.register(r'fullafgfs', views.FullTblUebersichtAfGfsViewSet, 'fullafgf')
router.register(r'fulltfs', views.FullTblTfsViewSet, 'fulltf')

router.register(r'changerequests', views.ChangeRequestsViewSet, 'changerequests')
router.register(r'schreibweisen', views.TblSchreibweisenViewSet, 'schreibweise')

admin.site.site_header = 'RechteDB - Adminseiten'
admin.site.site_title = 'RechteDB - Administration'
admin.site.index_title = 'RechteDB - Übersicht'

urlpatterns = [
    path('admin', admin.site.urls)
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# Use include() to add paths from the rapp application
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('rapp/', include('rapp.urls')),
    path('mdeditor/', include('mdeditor.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Das ist die wichtigste Zeile: / wird auf /rapp gemappt
urlpatterns += [
    path('', RedirectView.as_view(url='/rapp')),
]

urlpatterns += [
    url(r'^api/', include((router.urls, 'api'), namespace='myRDBNS')),
    path('', include('django.contrib.auth.urls')),
    path('myRDB/', include('myRDB.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

RechteDB/myRDB/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required,permission_required

from . import views

app_name = 'myRDB'
'''
    sets App urls
'''
urlpatterns = [
    #path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_reset/', views.Password_Reset.as_view(), name='password_reset'),
    path('register/', views.Register.as_view(), name='register'),
    path('profile/', login_required(views.Profile.as_view()), name='profile'),
    path('profile/rights_analysis', login_required(views.ProfileRightsAnalysis.as_view()), name='profile_rights_analysis'),
    path('profile/compare/', login_required(views.Compare.as_view()), name='compare'),
    path('csvToMongo/', permission_required('user.is_staff')(views.CSVtoMongoDB.as_view()), name='csvToMongo'),
    path('users/', permission_required('user.is_staff')(views.Users.as_view()), name='users'),
    #path('search_all/', permission_required('user.is_staff')(views.Search_All.as_view()), name='search_all'),
    path('request_pool/', permission_required('user.is_staff')(views.RequestPool.as_view()), name='request_pool'),
    path('my_requests/', login_required(views.MyRequests.as_view()), name='my_requests'),
    path('profile/compare/apply_changes/', login_required(views.RightApplication.as_view()), name='apply_changes'),
]

RechteDB/rapp/urls.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from . import view_UserHatRolle
from . import view_import
from . import stored_procedures
from . import view_serienbrief
from . import view_neueAFGF
from . import view_manuell

# app_name = 'rapp'        # Wird nur benötigt als namespace, falls mehrere Apps dieselbe Teil-URL haben

# Der Index als zentraler Einstieg
urlpatterns = [
    # klassenbasierter Aufruf
    # path('', views.IndexView.as_view(), name='index'),

    # Funktionsorientierte Form des Aufrufs
    path('', views.home, name='home'),
]

# Der Link auf die Gesamtliste
urlpatterns += [
    path('gesamtliste/', login_required(views.GesamtListView.as_view()), name='gesamtliste'),
]

# Der Link auf ein einzelnes Recht aus der Gesamtliste mit seiner generierten Detailsicht
urlpatterns += [
    path('gesamtliste/<int:pk>', login_required(views.GesamtDetailView.as_view()), name='gesamt-detail'),
]

# Der Link auf die User-liste
urlpatterns += [
    path('userliste/', login_required(views.UserIDundNameListView.as_view()), name='userliste'),
]

# Generische Formulare für CUD UserIDundName (werden im Frontend bedient)
urlpatterns += [
    path('user/<int:pk>/delete/', login_required(views.TblUserIDundNameDelete.as_view()), name='user-delete'),
    path('user/create/', login_required(views.TblUserIDundNameCreate.as_view()), name='user-create'),
    path('user/<int:pk>/update/', login_required(views.TblUserIDundNameUpdate.as_view()), name='user-update'),
    path('user/<int:pk>/toggle_geloescht/', login_required(views.userToggleGeloescht), name='user-toggle-geloescht'),
]

# Der Link auf die Team-liste
urlpatterns += [
    path('teamliste/', login_required(views.TeamListView.as_view()), name='teamliste'),
]

# Generische Formulare für CUD Orga (Teams, werden im Frontend bedient)
urlpatterns += [
    path('team/<int:pk>/delete/', login_required(views.TblOrgaDelete.as_view()), name='team-delete'),
    path('team/create/', login_required(views.TblOrgaCreate.as_view()), name='team-create'),
    path('team/<int:pk>/update/', login_required(views.TblOrgaUpdate.as_view()), name='team-update'),
]

# Der Link auf das Eingabepanel zur freien Selektion direkt auf der Gesamttabelle
urlpatterns += [
    path('panel/download', login_required(views.panelDownload), name='panel_download'),
    path('panel/', login_required(views.panel), name='panel'),
]

# Der Link auf das Eingabepanel zur freien Selektion auf der User-hat-Rolle Tabelle (UhR)
urlpatterns += [
    path('user_rolle_af/<int:pk>/delete/',
        login_required(view_UserHatRolle.UhRDelete.as_view()),
        name='user_rolle_af-delete'),
    path('user_rolle_af/<str:userid>/create/<str:rollenname>/<str:schwerpunkt_vertretung>',
        login_required(view_UserHatRolle.UhRCreate.as_view()),
        name='uhr_create'),
    path('user_rolle_af/<int:id>/',
         login_required(view_UserHatRolle.panel_UhR),
         name='user_rolle_af_parm'),
    path('user_rolle_af/export/<int:id>/',
         login_required(view_UserHatRolle.panel_UhR_af_export),
         name='user_rolle_af_export'),
    path('user_rolle_af/create/<str:userid>/',
         login_required(view_UserHatRolle.UhRCreate.as_view()),
         name='user_rolle_af-create' ),
    path('user_rolle_af/konzept/',
         login_required(view_UserHatRolle.panel_UhR_konzept),
         name='uhr_konzept'),
    path('user_rolle_af/konzept_pdf/',
         login_required(view_UserHatRolle.panel_UhR_konzept_pdf),
         name='uhr_konzept_pdf'),
    path('user_rolle_af/matrix/',
         login_required(view_UserHatRolle.panel_UhR_matrix),
         name='uhr_matrix'),
    path('user_rolle_af/matrix_csv/',
         login_required(view_UserHatRolle.panel_UhR_matrix_csv),
         name='uhr_matrix_csv'),
    path('user_rolle_af/matrix_csv/<str:flag>/',
         login_required(view_UserHatRolle.panel_UhR_matrix_csv),
         name='uhr_matrix_csv'),
    path('user_rolle_af/',
         login_required(view_UserHatRolle.panel_UhR),
         name='user_rolle_af'),
]

# Die Behandlujng der Beschreibungen manuell zu verwaltender Berechtigungen
# Hier sollte auch der mdeditor mitspielen
urlpatterns += [
    path('manuell/<int:pk>/delete/',
         login_required(view_manuell.Manuelle_BerechtigungDelete.as_view()), name='manuell_delete'),
    path('manuell/<int:pk>/update/',
         login_required(view_manuell.Manuelle_BerechtigungUpdate.as_view()), name='manuell_update'),
    path('manuell/create/',
         login_required(view_manuell.Manuelle_BerechtigungCreate.as_view()), name='manuell_create'),
    path('manuell/',
         login_required(view_manuell.Manuelle_BerechtigungListe.as_view()), name='manuell_liste'),
]

# URl zum Importieren neuer Daten aus IIQ (csv-File)
urlpatterns += [
    path('import/', login_required(view_import.import_csv), name='import'),
    path('import2/', login_required(view_import.import2), name='import2'),
    path('import2_quittung/', login_required(view_import.import2_quittung), name='import2_quittung'),
    path('import3_quittung/', login_required(view_import.import3_quittung), name='import3_quittung'),
    path('import_reset/', login_required(view_import.import_reset), name='import_reset'),
    path('import_status/', login_required(view_import.import_status), name='import_status'),
]

# URl zum Bestücken der verschiedenen Stored Procedures in das DBMS
urlpatterns += [
    path('stored_procedures/', login_required(stored_procedures.handle_stored_procedures), name='stored_procedures'),
]

# URl zum Erzeugen der LaTeX-Serienbriefinformation zu Direct Connects
urlpatterns += [
    path('einzelbrief/', login_required(view_serienbrief.einzelbrief), name='einzelbrief'),
    path('serienbrief/', login_required(view_serienbrief.serienbrief), name='serienbrief'),
]

# Finden neuer Kombiunationen aus AF und GF: Anzeige und spezifische Aktualisierung
urlpatterns += [
    path('neue_afgf/', login_required(view_neueAFGF.zeige_neue_afgf), name='zeige_neue_afgf'),
    path('neueAFGF_download/', login_required(view_neueAFGF.neue_afgf_download), name='neueAFGF_download'),
    path('neueAFGF_setzen/', login_required(view_neueAFGF.neueAFGF_setzen), name='neueAFGF_setzen'),
]

# URl zum Testen neuer Funktionalität (liegt in "Magie")
urlpatterns += [
    path('magic_click/', login_required(views.magic_click), name='magic_click'),
]

RechteDB/myRDB/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, UsernameField
from django.utils.safestring import mark_safe

from django.contrib.auth import get_user_model

#from .models import User, Orga, Group, Department, ZI_Organisation, Role, AF, GF, TF, User_AF, User_GF, User_TF, \
#    ChangeRequests
from .models import *


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ('identity',)



class CustomUserCreationForm(UserCreationForm):
    
    #    Form for password and xvNumber validation
     #   also checks if Profile has already been activated by any user by creating pswd
      #      otherwise create new
    
    class Meta:
        model = get_user_model()
        fields = ('username','email', 'first_name', 'last_name',)

    def clean(self):
        print("in clean_password2")
        cd = self.cleaned_data
        password1 = cd.get("password1")
        password2 = cd.get("password2")
        if password1 and password2 and password1 != password2:
            print("in passwords dont match")

            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )

        return cd

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        username = self.cleaned_data['username']
        username_upper = username.upper()
        print("in save!")
        print(username, username_upper)
        try:
            user = User.objects.get(username=username)
            print("User: ", user.__str__(), " mit username_lower existiert")
            if user.password == "":
                print("User mit username_lower existiert - password is leer -> pw wird gesafet")
                user.set_password(self.cleaned_data['password1'])
                user.save()
            else:
                print("User mit username_lower existiert und hat pw!")
                forms.ValidationError("User mit username_lower existiert und hat pw!")
                return user
                # messages.info(HttpRequest(),"User exists and has a Password")
        except(KeyError, User.DoesNotExist):
            try:
                user = User.objects.get(username=username_upper)
                print("User: ", user.__str__(), " mit Identity_upper existiert")
                if user.password == "":
                    print("User mit username_upper existiert - password is leer -> pw wird gesafet")
                    user.set_password(self.cleaned_data['password1'])
                    user.save()
                else:
                    forms.ValidationError("User mit username_upper existiert und hat pw!")
                    print("User mit username_upper existiert und hat pw!")
                return user
                # messages.info(HttpRequest(),"User exists and has a Password")
            except(KeyError, User.DoesNotExist):
                print("User existiert nicht - wird neu angelegt")
                user = super(CustomUserCreationForm, self).save(commit=False)
                user.set_password(self.cleaned_data['password1'])
                username_numerics = username[2:]
                print(username_numerics)
                if commit:
                    user.save()
                    userid_names = TblUserIDundName.objects.filter(userid__endswith=username_numerics)
                    for userid_name in userid_names:
                        user.userid_name.add(userid_name.id)

        return user

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = ('username',)
        error_css_class = 'error'


class SomeForm(forms.Form):
    start_import = forms.FileInput()


class ApplyRightForm(forms.Form):
    reason_for_application = forms.CharField(widget=forms.Textarea(attrs={'rows': '4'}), min_length=20, max_length=500,
                                             label=mark_safe('<strong>Grund der Beantragung:</strong>'))


class DeleteRightForm(forms.Form):
    reason_for_deletion = forms.CharField(widget=forms.Textarea(attrs={'rows': '4'}), min_length=20, max_length=500,
                                          label=mark_safe('<strong>Grund der Löschung:</strong>'))


class AcceptChangeForm(forms.Form):
    change_in_IIQ_check = forms.BooleanField(label="Änderungen in IIQ beantragt?")


class DeclineChangeForm(forms.Form):
    reason_for_decline = forms.CharField(widget=forms.Textarea(attrs={'rows': '2'}), min_length=20, max_length=500,
                                         label=mark_safe('<strong>Grund der Ablehnung:</strong>'))

class ProfileHeaderForm(forms.Form):
    user_search = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder': 'vergleiche mit...'}))

RechteDB/myRDB/templates/myRDB/base.html
<!DOCTYPE html>
<meta charset="UTF-8">

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="{% static 'myRDB/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'myRDB/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'myRDB/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'myRDB/js/d3.v4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'myRDB/js/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'myRDB/js/bootbox.min.js' %}"></script>

    <title>{% block title %}MyRDB{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/jquery-ui.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/circle_packing/circlePacking.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/scatter_plot/scatterPlot_fromJSON.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/style.css' %}">
    {% if view_mode == "Tabellarische Ansicht" %}
        <script type="text/javascript" src="{% static 'myRDB/js/datatables.min.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/datatables.min.css'%}">
    {% endif %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'myRDB:index' %}">MyRDB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav navbar-left">
            {% if user.is_authenticated %}
                <li><a class="nav-item nav-link" href="{% url 'myRDB:profile' %}">Profil</a></li>
                <li><a class="nav-item nav-link" href="{% url 'myRDB:my_requests' %}">Meine Anfragen</a></li>
                {% if user.is_staff %}
                    <li><a class="nav-item nav-link" href="{% url 'myRDB:users' %}">Nutzer</a></li>
                    <li><a class="nav-item nav-link" target="_blank" href="{% url 'home' %}">Suche (Rapp)</a></li>
                    <li><a class="nav-item nav-link" href="{% url 'myRDB:request_pool' %}">Anfragen-Pool</a></li>
                    <li><a class="nav-item nav-link disabled" href="{% url 'myRDB:csvToMongo' %}">Datenimport</a></li>
                {% endif %}
            {% endif %}
        </ul>

    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $("disabled").click(function () {
                return false;
            });
        });
    </script>
    <ul class="nav navbar-right navbar-nav">
        {% if user.is_authenticated %}
        <li><p>Verlassen: </p></li>
        <li><a class="nav-item nav-link active" href="{% url 'myRDB:logout' %}">Logout<span
                class="sr-only">(current)</span></a></li>
        {% else %}
        <li><p>Einloggen: </p></li>
        <li><a class="nav-item nav-link active" href="{% url 'myRDB:login' %}">Login<span
                class="sr-only">(current)</span></a></li>
        {% endif %}

    </ul>
</nav>


<div class="content container" id="content_container">
    {% block content %}
    {% endblock %}
</div>
</body>

</html>

RechteDB/myRDB/templates/myRDB/circlePackingTemplate.html
{% load static %}
{% load asjson %}
{# Hier die Circle-Packing-Visualisierung #}
{% csrf_token %}
<div class="card-header">
    <h5>Berechtigungsgraph</h5>
</div>
<div class="card-body">
    <script>
        var CSRF_TOKEN = "{{ csrf_token }}";
        var updateCP;
    </script>
    <svg id="circlePackingSVG" width="480" height="480"></svg>
    <script type="text/javascript" src="{% static 'myRDB/js/circle_packing/circlePacking.js' %}"></script>
</div>
<div class="card-footer">
    <p class="card-text">Berechtigungen mit Rechtsklick & Bestätigung auf Löschliste setzen!</p>
</div>

RechteDB/myRDB/templates/myRDB/csvToMongo.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>hier wird aus csv mongo</h1>
<form action="?start_import" method="post">
    {% csrf_token %}
    <label for="start_import">start your csv-import: </label>
    <input id="start_import" type="file" name="start_import">
    <input type="submit" value="start import">
</form>
{# TODO: Assynchron & ProgressBar #}
{% endblock %}

RechteDB/myRDB/templates/myRDB/detail.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myRDB:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock %}

RechteDB/myRDB/templates/myRDB/index.html
{% extends 'myRDB/base.html' %}
{% block title %}MyRDB - Home{% endblock %}
{% block content %}
    <h1 class="top-buffer"><b>Wilkommen in der RechteDB</b></h1>
{% if user.is_authenticated %}
    <p class="top-buffer"><b>Hi {{user.username}} !</b></p>
    <p>Über den Menüpunkt <a href="{% url 'myRDB:profile' %}"> <i>Profil</i></a> gelangen Sie zu Ihrer Berechtigungsübersicht und allen von dort aus ausführbaren Aktionen.</p>
    <p><a href="{% url 'myRDB:my_requests' %}"><i>Meine Anfragen</i></a> führt Sie zu einer Übersicht Ihrer gestellten Berechtigungsanfragen.</p>
    {% if user.is_staff %}
        <p>
            Mit <a href="{% url 'myRDB:users' %}"><i>Nutzer</i></a> laden Sie eine Listung aller berechtigten Nutzer, über welche Sie auch auf deren Profile
            zugreifen und dadurch Nutzer-Berechtigungsdaten ändern können.
        </p>
        <p>
            <a target="_blank" href="{% url 'home' %}"><i>Suche (Rapp)</i></a> stellt eine Verlinkung zur <i><b>Rapp-Application</b></i> dar.
        </p>
        <p>
            Im <a href="{% url 'myRDB:request_pool' %}"><i>Anfragen-Pool</i></a> finden Sie alle gestellten Anfragen der Nutzer und können diese Beantworten.
        </p>
    {% endif %}
    <p>
        <b>
            Falls Sie Sich zum ersten Mal anmelden oder nach Ihrem letzten Besuch eine Datenaktualisierung stattgefunden hat,
            benötigt das Aktualisieren einen Augenblick. Wir bitten um Verständnis!
        </b>
    </p>
    <p><a href="{% url 'myRDB:logout' %}">logout</a></p>
{% else %}

<p>Um Ihre Berechtigungsdaten anzuzeigen loggen Sie sich bitte ein!</p>
<a href="{% url 'myRDB:login' %}">login</a>
<a href="{% url 'myRDB:register' %}">sign up</a>
{% endif %}

{% endblock %}

RechteDB/myRDB/templates/myRDB/navbar.html
{% extends 'myRDB/base.html' %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav navbar-left">
            {% if user.is_authenticated %}
            <li><a class="nav-item nav-link" href="{% url 'myRDB:profile' %}">Profile</a></li>
            <li><a class="nav-item nav-link" href="{% url 'myRDB:csvToMongo' %}">CSVintoMongoDB</a></li>
            <li><a class="nav-item nav-link disabled" href="#">Disabled</a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><p>Youre logged in</p></li>
            <li><a class="nav-item nav-link active" href="{% url 'myRDB:logout' %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li><p>Youre not logged in</p></li>
            <li><a class="nav-item nav-link active" href="{% url 'myRDB:login' %}">Login<span
                    class="sr-only">(current)</span></a></li>
            {% endif %}

        </ul>
    </div>
</nav>

{% endblock %}

RechteDB/myRDB/templates/myRDB/results.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'myRDB:detail' question.id %}">Vote again?</a>
{% endblock %}